---
- name: apache server installed
  hosts: all
  become: yes
  tasks:
  - name: install apache
    yum:
      name: httpd
      state: latest
  - name: enable and start apache
    service:
      name: httpd
      state: started
      enabled: true
  - name: send index.html
    copy:
      src: "{{stage}}_index.html"
      dest: /var/www/html/index.html
